modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://github.com/GizmoTheMoonPig/OpenBlocksTrophies/issues"

[[mods]]
modId = "obtrophies"
version = "${file.jarVersion}"
displayName = "OpenBlocks Trophies"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/openblocks-trophies"
logoFile = "trophy.png"
credits = "Original Trophies made by the OpenMods team"
authors = "GizmoTheMoonPig"
description = '''
Brings back the trophies from OpenBlocks.
'''

[[dependencies.obtrophies]]
modId = "neoforge"
type = "required"
versionRange = "[21.0.0-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.obtrophies]]
modId = "minecraft"
type = "required"
versionRange = "[1.21]"
ordering = "NONE"
side = "BOTH"
